# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrule = opacity 0.89 override 0.89 override, match:class .*

# Enable blur for xwayland context menus
windowrule = no_blur on, match:xwayland 1

# Enable blur for every window
windowrule = no_blur off, match:class .*

workspace = s[false], gapsout:30
workspace = s[true], gapsout:50
windowrule = match:class vesktop, workspace special:1
windowrule = match:class spotify, workspace special:4
